# Generated by Django 2.2.12 on 2021-11-20 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_jobpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobPost',
        ),
    ]
