# Generated by Django 2.2.12 on 2021-11-20 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_delete_jobpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('shop', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=10000)),
                ('content', models.TextField()),
                ('external_link', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_due', models.DateTimeField()),
            ],
        ),
    ]
