# Generated by Django 3.1.7 on 2021-11-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_promotionpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumpost',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AlterModelOptions(
            name='jobpost',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AlterModelOptions(
            name='promotionpost',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='date_due',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='promotionpost',
            name='date_due',
            field=models.CharField(max_length=100),
        ),
    ]
